[[main]]
none = "none"

[[main]]
name = "Posts"
pageRef = "posts"
identifier = "RZkRI4FTQ5"
weight = 2

[[main]]
name = "About"
pageRef = "about"
identifier = "FlywHKGeIe"
weight = 1

[[main]]
pre = "github"
url = "https://github.com/tomfieber"
identifier = "cGKObBbwuA"
weight = 9_999

[[main]]
pre = "youtube"
url = "https://www.youtube.com/@pawpawhacks"
identifier = "l8n9sXo7m2A"
weight = 9_999

[[main]]
pre = "discord"
url = "https://discord.gg/pjUUkw38mC"
identifier = "eYq7WapuDLU"
weight = 9_999

[[footer]]
none = "none"

[[footer]]
name = "Tags"
pageRef = "tags"
identifier = "YYlvo6ZfyT"
weight = 1

[[footer]]
name = "Categories"
pageRef = "categories"
identifier = "xyJeselrlV"
weight = 2
