colorScheme = "autumn"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableA11y = false
enableSearch = true
enableCodeCopy = true
enableStructuredBreadcrumbs = false
replyByEmail = false
disableImageOptimization = false
disableImageOptimizationMD = false
disableTextInHeader = false
hotlinkFeatureImage = false
fingerprintAlgorithm = "sha512"
giteaDefaultServer = "https://git.fsfe.org"
forgejoDefaultServer = "https://v11.next.forgejo.org"
fathomAnalytics = { }
umamiAnalytics = { }
selineAnalytics = { }
verification = { }
rssnext = { }
advertisement = { }
smartTOC = true
defaultBackgroundImage = "tie-dye-background.png"
defaultSocialImage = "morning-coffee.png"

[buymeacoffee]
identifier = "pawpawhacks"
globalWidget = true
globalWidgetMessage = ""
globalWidgetColor = ""
globalWidgetPosition = ""

[firebase]
apiKey = "AIzaSyARKk9W0yHKqxPgF5ZFwzaDbphW3GVsYic"
authDomain = "blowfish-5869c.firebaseapp.com"
projectId = "blowfish-5869c"
storageBucket = "blowfish-5869c.firebasestorage.app"
messagingSenderId = "74547788078"
appId = "1:74547788078:web:11cbf9b22aab83885ea2bf"
measurementId = "G-RYKK74M9PF"

[header]
layout = "basic"

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "background"
showRecent = true
showRecentItems = 5
showMoreLink = false
showMoreLinkDest = "/posts/"
cardView = false
cardViewScreenWidth = false
layoutBackgroundBlur = false
disableHeroImageFilter = false

[article]
showDate = true
showViews = true
showLikes = false
showDateOnlyInArticle = false
showDateUpdated = false
showAuthor = true
showHero = true
heroStyle = "background"
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showTaxonomies = false
showCategoryOnly = true
showAuthorsBadges = true
showWordCount = false
showZenMode = true
showAuthorBottom = true
showSummary = true
sharingLinks = [ "twitter", "linkedin", "facebook", "email", "line" ]

[list]
showHero = true
heroStyle = "background"
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showSummary = true
showViews = false
showLikes = false
showTableOfContents = false
showCards = false
orderByWeight = false
groupByYear = true
cardView = false
cardViewScreenWidth = false
constrainItemsWidth = false

[sitemap]
excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
showTermCount = true
showHero = true
heroStyle = "background"
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
cardView = false

[term]
showHero = true
heroStyle = "background"
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = false
groupByYear = false
cardView = false
cardViewScreenWidth = false

[leaf]
showViews = false
