site_name: The Okayest Pentester
site_url: https://tomfieber.github.io/
repo_url: https://github.com/tomfieber/tomfieber.github.io
repo_name: tomfieber/tomfieber.github.io
theme:
  palette: 
    # Palette toggle for automatic mode
    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      accent: deep orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent: deep orange 
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs.sticky
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.footer
    - navigation.top
    - search.suggest
    - content.code.copy
plugins:
  - blog:
      blog_toc: true
      post_dir: "{blog}/articles"
      post_date_format: full
      post_url_date_format: yyyy/MM/dd
      post_url_format: "{date}/{slug}"
      post_excerpt_max_categories: 2
      post_excerpt_separator: <!-- more -->
      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      post_excerpt: required
      post_excerpt_separator: <!-- more -->
      archive: true
      archive_name: Archive
      archive_date_format: yyyy
      archive_url_format: "archive/{date}"
      authors_file: "{blog}/.authors.yml"
  - search
  - tags
markdown_extensions:
  - admonition
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

extra:
  analytics: 
    provider: google
    property: G-HH4Y2D319L
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.

# Copyright
copyright: Copyright &copy; 2016 - 2025 Tom Fieber

# not_in_nav: |
#   /notes/**/*.md

nav:
  - Home: index.md
  - Web:
    - web/index.md
    - Checklists:
      - Information Gathering: web/checklists/01-information-gathering.md
      - Configuration Management and Deployment Testing: web/checklists/02-configuration-management-deployment-testing.md
      - Identity Management Testing: web/checklists/03-identity-management-testing.md
      - Authentication Testing: web/checklists/04-authentication-testing.md
      - Authorization Testing: web/checklists/05-authorization-testing.md
      - Session Management Testing: web/checklists/06-session-management-testing.md
      - Input Validation Testing: web/checklists/07-input-validation-testing.md
      - Error Handling: web/checklists/08-error-handling.md
      - Testing Weak Cryptography: web/checklists/09-testing-weak-cryptography.md
      - Business Logic Testing: web/checklists/10-business-logic-testing.md
      - Client-Side Testing: web/checklists/11-client-side-testing.md
      - API Testing: web/checklists/12-api-testing.md
  - Infrastructure:
    - infrastructure/index.md
    - Checklsits:
      - Network Enumeration: infrastructure/internal/network-enumeration.md
      - Domain Testing: 
        - Domain Data: infrastructure/internal/domain-data.md
        - Domain Vulnerability Scanning: infrastructure/internal/domain-vuln-scanning.md
        - Domain SMB Checks: infrastructure/internal/smb.md
  - Notes:
    - notes/index.md
    - General:
      - Scanning: notes/nmap.md
      - Low Hanging Fruit: notes/low-hanging-fruit.md
      - Footprinting:
        - FTP: notes/ftp.md
        - SSH: notes/ssh.md
    - Web:
      - CORS: notes/cors.md
      - Cross-Site Scripting: notes/xss.md
      - Injection:
        - Command Injection: notes/command-injection.md
        - SQL Injection: notes/sqli.md
    - Cloud:
      - Azure: notes/azure.md
  - Blog:
    - blog/index.md
  - CV:
    - cv/index.md