site_name: The Okayest Pentester
site_url: https://tomfieber.github.io/
repo_url: https://github.com/tomfieber/tomfieber.github.io
repo_name: tomfieber/tomfieber.github.io
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.sticky
    - navigation.sections
    - search.suggest
plugins:
  - blog
nav:
  - index.md
  - Blog
    - blog/index.md
