authors:
  tomfieber:
    name: "Tom Fieber"        # Author name
    description: Dad, husband, okay pentester # Author description
    avatar: url         # Author avatar
    slug: "tomfieber"           # Author profile slug
    url: "https://github.com/tomfieber"            # Author website URL